//! Byte-exact parity tests against reference messages produced by the C
//! compiler from the *unmodified* firmware ABI headers.
//!
//! The committed `tests/golden/*.bin` files were generated by
//! `tests/golden/gen/gen_golden.c`, which `#include`s the real kernel headers
//! and dumps the raw struct bytes. Each test below builds the same logical
//! message through the safe API and asserts the serialized output is identical,
//! proving the Rust port is a drop-in ABI replacement.

use ipu4_fw_msgs::*;

fn golden(name: &str) -> Vec<u8> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/");
    std::fs::read(format!("{path}{name}")).unwrap_or_else(|e| panic!("read {name}: {e}"))
}

/// Mirrors the `stream_cfg_full.bin` case in the C generator.
fn build_stream_cfg_full() -> StreamCfgData {
    let isa_cfg = IsaConfig {
        isa_res: [Resolution::new(100, 200), Resolution::new(300, 400)],
        blc: true,
        ae: true,
        paf: 0x5a,
        send_resp_stats_ready: true,
        ..Default::default()
    };
    let mut b = StreamCfgData::builder()
        .isa_cfg(isa_cfg)
        .compfmt(0xdead_beef)
        .send_irq_sof_discarded(true)
        .send_resp_eof_discarded(true)
        .src(2)
        .vc(1)
        .isl_use(IslUse::SingleIsa);
    for i in 0..4i32 {
        b = b
            .crop(
                i as usize,
                Cropping {
                    top_offset: i + 1,
                    left_offset: -(i + 1),
                    bottom_offset: 1000 + i,
                    right_offset: 2000 + i,
                },
            )
            .unwrap();
    }
    for i in 0..4u32 {
        b = b
            .add_input_pin(InputPinInfo {
                input_res: Resolution::new(1920 + i, 1080 + i),
                dt: 0x2b, // RAW_10
                mipi_store_mode: 1,
                bits_per_pix: 0, // filled by auto_bits_per_pix
            })
            .unwrap();
    }
    for i in 0..6u32 {
        b = b
            .add_output_pin(OutputPinInfo {
                output_res: Resolution::new(1920, 1080),
                stride: 3840,
                watermark_in_lines: i,
                send_irq: 1,
                input_pin_id: (i % 4) as u8,
                pt: 0,
                ft: 20,
                online: 1,
            })
            .unwrap();
    }
    b.auto_bits_per_pix(true).build().unwrap()
}

/// Mirrors the `stream_cfg_min.bin` case in the C generator.
fn build_stream_cfg_min() -> StreamCfgData {
    StreamCfgData::builder()
        .add_input_pin(InputPinInfo {
            input_res: Resolution::new(640, 480),
            dt: 0x24, // RGB_888
            mipi_store_mode: 0,
            bits_per_pix: 0,
        })
        .unwrap()
        .auto_bits_per_pix(true)
        .build()
        .unwrap()
}

/// Mirrors the `frame_buff_set.bin` case in the C generator.
fn build_frame_buff_set() -> FrameBuffSet {
    let mut b = FrameBuffSet::builder()
        .process_group_light(ParamPin::new(BufferId(0x11), CssVirtualAddress(0x22)))
        .send_irq_sof(true)
        .send_resp_eof(true);
    for i in 0..6u64 {
        b = b
            .add_output_pin(OutputPinPayload::new(
                BufferId(0x1000 + i),
                CssVirtualAddress(0x2000 + i as u32),
            ))
            .unwrap();
    }
    b.build().unwrap()
}

#[test]
fn stream_cfg_full_matches_c() {
    let cfg = build_stream_cfg_full();
    assert_eq!(cfg.serialize(), golden("stream_cfg_full.bin"));
    // bits_per_pix was filled from the data-type table, matching C.
    assert_eq!(cfg.input_pins[0].bits_per_pix, 10);
}

#[test]
fn stream_cfg_min_matches_c() {
    let cfg = build_stream_cfg_min();
    assert_eq!(cfg.serialize(), golden("stream_cfg_min.bin"));
    assert_eq!(cfg.input_pins[0].bits_per_pix, 24);
}

#[test]
fn frame_buff_set_matches_c() {
    assert_eq!(
        build_frame_buff_set().serialize(),
        golden("frame_buff_set.bin")
    );
}

#[test]
fn send_token_matches_c() {
    let tok = SendQueueToken::complex(
        BufferId(0xabcd_ef01_2345_6789),
        CssVirtualAddress(0x1234),
        SendType::StreamCapture,
    );
    assert_eq!(tok.serialize(), golden("send_token.bin"));
}

#[test]
fn proxy_send_token_matches_c() {
    let tok = ProxySendQueueToken::new(0x1111_1111, 0x2222_2222, 0x3333_3333, 0x4444_4444);
    assert_eq!(tok.serialize(), golden("proxy_send_token.bin"));
}

#[test]
fn resp_info_matches_c() {
    let resp = RespInfo {
        buf_id: BufferId(0xcafe_f00d),
        pin: OutputPinPayload::new(BufferId(0x55), CssVirtualAddress(0x66)),
        process_group_light: ParamPin::new(BufferId(0x77), CssVirtualAddress(0x88)),
        error_info: ErrorInfo {
            error: IsysError::HwConsistency,
            error_details: 0x99,
        },
        timestamp: [0xaaaa, 0xbbbb],
        stream_handle: 3,
        resp_type: RespType::PinDataReady,
        pin_id: 2,
        acc_id: 1,
    };
    assert_eq!(resp.serialize(), golden("resp_info.bin"));
}

#[test]
fn proxy_resp_info_matches_c() {
    let presp = ProxyRespInfo {
        request_id: 0x1234_5678,
        error_info: ProxyErrorInfo {
            error: ProxyError::InvalidWriteOffset,
            error_details: 0xdcba,
        },
    };
    assert_eq!(presp.serialize(), golden("proxy_resp_info.bin"));
}

/// The golden bytes must also parse back into the expected logical message.
#[test]
fn golden_bytes_deserialize_back() {
    assert_eq!(
        StreamCfgData::deserialize(&golden("stream_cfg_full.bin")).unwrap(),
        build_stream_cfg_full()
    );
    assert_eq!(
        FrameBuffSet::deserialize(&golden("frame_buff_set.bin")).unwrap(),
        build_frame_buff_set()
    );
    let resp = RespInfo::deserialize(&golden("resp_info.bin")).unwrap();
    assert_eq!(resp.resp_type, RespType::PinDataReady);
    assert_eq!(resp.error_info.error, IsysError::HwConsistency);
    assert_eq!(resp.buf_id, BufferId(0xcafe_f00d));
}
