//! `dw9714-sys` — raw, manually-written FFI bindings for the dw9714 VCM
//! (voice-coil motor) lens-actuator driver.
//!
//! This crate is a faithful, hand-written translation of the public C surface
//! of `drivers/media/i2c/dw9714.c` and `include/media/dw9714.h`. It is **not**
//! generated by `bindgen`; every type, constant and function signature mirrors
//! the original kernel C so the higher-level safe [`dw9714`] crate can build a
//! memory-safe abstraction on top of it.
//!
//! Everything in this crate is `unsafe` to use directly: the types are raw
//! `#[repr(C)]` mirrors of kernel structures and the functions are
//! `extern "C"` declarations whose symbols are resolved against the Linux
//! kernel (or, for the pure-logic pieces, re-implemented in the safe crate).
//!
//! [`dw9714`]: https://docs.rs/dw9714
#![no_std]

use core::ffi::{c_char, c_int, c_void};

// ---------------------------------------------------------------------------
// Constants (faithful mirror of include/media/dw9714.h)
// ---------------------------------------------------------------------------

/// I2C driver / module name (`DW9714_NAME`).
pub const DW9714_NAME: &[u8] = b"dw9714\0";

/// Maximum absolute focus position (`DW9714_MAX_FOCUS_POS`, 10-bit DAC).
pub const DW9714_MAX_FOCUS_POS: u16 = 1023;

/// Lens ramp step size (`DW9714_CTRL_STEPS`). Must stay a power of two.
pub const DW9714_CTRL_STEPS: u16 = 16;

/// Per-step settling delay in microseconds (`DW9714_CTRL_DELAY_US`).
pub const DW9714_CTRL_DELAY_US: u32 = 1000;

/// Default VCM mode/step nibble (`VCM_DEFAULT_S`).
pub const VCM_DEFAULT_S: u16 = 0x0;

// ---------------------------------------------------------------------------
// errno values used by the driver (negated on return, Linux ABI)
// ---------------------------------------------------------------------------

/// `-EIO`: I/O error.
pub const EIO: c_int = 5;
/// `-ENOMEM`: out of memory.
pub const ENOMEM: c_int = 12;
/// `-ENODEV`: no such device.
pub const ENODEV: c_int = 19;
/// `-EINVAL`: invalid argument.
pub const EINVAL: c_int = 22;

// ---------------------------------------------------------------------------
// I2C message flags (mirror of <linux/i2c.h>)
// ---------------------------------------------------------------------------

/// Read data (from slave to master). Absence means write.
pub const I2C_M_RD: u16 = 0x0001;

/// V4L2 control id for absolute focus (`V4L2_CID_FOCUS_ABSOLUTE`).
///
/// `V4L2_CID_CAMERA_CLASS_BASE + 10` in the kernel UAPI.
pub const V4L2_CID_FOCUS_ABSOLUTE: u32 = 0x009a_090a;

// ---------------------------------------------------------------------------
// `VCM_VAL` macro, faithfully expressed as a const fn.
// ---------------------------------------------------------------------------

/// `VCM_VAL(data, s)` — pack a 10-bit lens position `data` and a 4-bit
/// mode/step nibble `s` into the 16-bit register word written over I2C.
///
/// Faithful translation of `#define VCM_VAL(data, s) (u16)((data) << 4 | (s))`.
#[inline]
#[must_use]
pub const fn VCM_VAL(data: u16, s: u16) -> u16 {
    (data << 4) | s
}

// ---------------------------------------------------------------------------
// Opaque kernel types
//
// These are kernel-internal structures the driver only ever handles by
// pointer. They are represented as opaque, non-constructible types so the FFI
// layer can pass pointers around without claiming to know their layout.
// ---------------------------------------------------------------------------

macro_rules! opaque_type {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[repr(C)]
        pub struct $name {
            _data: [u8; 0],
            _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
        }
    };
}

opaque_type!(/// Opaque `struct device`.
    device);
opaque_type!(/// Opaque `struct i2c_adapter`.
    i2c_adapter);
opaque_type!(/// Opaque `struct v4l2_ctrl`.
    v4l2_ctrl);
opaque_type!(/// Opaque `struct v4l2_ctrl_handler`.
    v4l2_ctrl_handler);
opaque_type!(/// Opaque `struct v4l2_subdev`.
    v4l2_subdev);
opaque_type!(/// Opaque `struct v4l2_subdev_fh`.
    v4l2_subdev_fh);

/// Mirror of the relevant prefix of `struct i2c_client`.
///
/// Only the fields the dw9714 driver reads (`addr`, `adapter`, `dev`) are
/// modelled; the kernel struct has many more, hence this is **not** a complete
/// layout and must only be accessed behind a pointer originating from the
/// kernel.
#[repr(C)]
pub struct i2c_client {
    /// Slave address (`client->addr`).
    pub addr: u16,
    /// Owning adapter (`client->adapter`).
    pub adapter: *mut i2c_adapter,
    /// Embedded device (`client->dev`).
    pub dev: *mut device,
}

/// Mirror of `struct i2c_msg` (`<linux/i2c.h>`).
#[repr(C)]
pub struct i2c_msg {
    /// Slave address.
    pub addr: u16,
    /// Flags (e.g. [`I2C_M_RD`]). `0` for a plain write.
    pub flags: u16,
    /// Number of bytes in `buf`.
    pub len: u16,
    /// Pointer to the message payload.
    pub buf: *mut u8,
}

/// Mirror of `struct dw9714_platform_data` (`include/media/dw9714.h`).
#[repr(C)]
pub struct dw9714_platform_data {
    /// Backing image sensor whose power domain gates the VCM.
    pub sensor_dev: *mut device,
    /// xshutdown GPIO. Negative if unused.
    pub gpio_xsd: c_int,
}

/// Mirror of the dw9714 driver's private device structure
/// (`struct dw9714_device`). Layout is faithful to the C definition; opaque
/// kernel members are represented by pointers/opaque embeds.
#[repr(C)]
pub struct dw9714_device {
    /// Owning I2C client.
    pub client: *mut i2c_client,
    /// V4L2 control handler (embedded in the C struct).
    pub ctrls_vcm: v4l2_ctrl_handler,
    /// V4L2 sub-device (embedded in the C struct).
    pub subdev_vcm: v4l2_subdev,
    /// Optional platform data.
    pub pdata: *mut dw9714_platform_data,
    /// Last value programmed into the VCM DAC (`current_val`).
    pub current_val: u16,
}

/// Mirror of `struct i2c_device_id`.
#[repr(C)]
pub struct i2c_device_id {
    /// NUL-terminated device name.
    pub name: [c_char; 20],
    /// Driver-private data.
    pub driver_data: usize,
}

// ---------------------------------------------------------------------------
// Foreign function declarations.
//
// These mirror the kernel symbols the dw9714 driver depends on. They are
// declared here for signature fidelity; resolving them requires linking
// against the kernel. The safe `dw9714` crate does not call these directly —
// it routes hardware access through a Rust trait — so a normal `cargo test`
// build never references (and therefore never needs to link) these symbols.
// ---------------------------------------------------------------------------

extern "C" {
    /// `int i2c_transfer(struct i2c_adapter *adap, struct i2c_msg *msgs, int num);`
    pub fn i2c_transfer(adap: *mut i2c_adapter, msgs: *mut i2c_msg, num: c_int) -> c_int;

    /// `int i2c_adapter_id(struct i2c_adapter *adap);`
    pub fn i2c_adapter_id(adap: *mut i2c_adapter) -> c_int;

    /// `int pm_runtime_get_sync(struct device *dev);`
    pub fn pm_runtime_get_sync(dev: *mut device) -> c_int;

    /// `int pm_runtime_put(struct device *dev);`
    pub fn pm_runtime_put(dev: *mut device) -> c_int;

    /// `int pm_runtime_put_sync(struct device *dev);`
    pub fn pm_runtime_put_sync(dev: *mut device) -> c_int;

    /// `void pm_runtime_enable(struct device *dev);`
    pub fn pm_runtime_enable(dev: *mut device);

    /// `void pm_runtime_disable(struct device *dev);`
    pub fn pm_runtime_disable(dev: *mut device);

    /// `void gpio_set_value(unsigned int gpio, int value);`
    pub fn gpio_set_value(gpio: c_int, value: c_int);

    /// `void usleep_range(unsigned long min, unsigned long max);`
    pub fn usleep_range(min: u64, max: u64);

    /// `void *devm_kzalloc(struct device *dev, size_t size, gfp_t flags);`
    pub fn devm_kzalloc(dev: *mut device, size: usize, flags: u32) -> *mut c_void;
}
